anypoint.host=anypoint.mulesoft.com
access.token.path=/accounts/api/v2/oauth2/token
anypoint.profile.path=/accounts/api/profile
anypoint.get.usage.count=/metering/usage/api/v1/meters:search

schedular.expression=0 0 18 * * ?
schedular.timezone=UTC

usage.percentage=10
max.retries=3
retries.second=30000

http.max.connection=-1
http.connectionIdle.timeout=30000
http.response.bufferSize=1024

outlook.sendEmail.baseUrl=https://graph.microsoft.com/v1.0
outlook.sendEmail.tokenUrl=https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token
outlook.sendEmail.scopes=https://graph.microsoft.com/.default