access.token.clientId=![rnLpdQI7AcURuGaH5ENmHK28ANnALTcTAb8hh0BVPtMHN51mjBxIm89Pt2Eqb8ew]
access.token.clientSecret=![pE00c5ASK+0lHJL+RLoYEMpJcL9EM5sGSuK+LflP9558hjvUb3MwQB4NicfV0Uzf]

outlook.sendEmail.clientId=![QIUQSwWi5m2zFHK6GOT8VLyf8ycvIqWef7CDPChfKl6AABvh4Rb12bVT8LB47ZQA]
outlook.sendEmail.clientSecret=![sgnTLeZxxJJZT5sBxqIM+VZMg+5Q6x3hp/i5sc/uWm6xmiKlpIvGB6JuGanRcnAG]
